# Generated by Django 4.0.3 on 2022-03-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-name']},
        ),
    ]
