# Generated by Django 4.0.4 on 2022-04-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default=None, upload_to='students'),
            preserve_default=False,
        ),
    ]
